updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,29 +66,29 @@ jobs:
           yq --version
 
 
-      # Step 3: Set up SOPS age key
-      # - name: Set Up SOPS Key
-      #   run: |
-      #     echo "${{ secrets.SOPS_AGE_KEY }}" > ./sops-age-key.txt
-      #     export SOPS_AGE_KEY_FILE=./sops-age-key.txt
-      #   env:
-      #     SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
+      Step 3: Set up SOPS age key
+      - name: Set Up SOPS Key
+        run: |
+          echo "${{ secrets.SOPS_AGE_KEY }}" > ./sops-age-key.txt
+          export SOPS_AGE_KEY_FILE=./sops-age-key.txt
+        env:
+          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
 
-      # - name: Decrypt Secrets File
-      #   id: fetch_secrets
-      #   run: |
-      #     # Define the path to secrets file
-      #     SECRETS_FILE_PATH="./deploy-as-code/helm/environments/${{ github.event.inputs.env_file }}-secrets.yaml"
+      - name: Decrypt Secrets File
+        id: fetch_secrets
+        run: |
+          # Define the path to secrets file
+          SECRETS_FILE_PATH="./deploy-as-code/helm/environments/${{ github.event.inputs.env_file }}-secrets.yaml"
 
-      #     # Check if the secrets file exists
-      #     if [ ! -f "$SECRETS_FILE_PATH" ]; then
-      #       echo "Error: Secrets file not found at $SECRETS_FILE_PATH"
-      #       exit 1
-      #     fi
+          # Check if the secrets file exists
+          if [ ! -f "$SECRETS_FILE_PATH" ]; then
+            echo "Error: Secrets file not found at $SECRETS_FILE_PATH"
+            exit 1
+          fi
           
-      #     # Decrypt only the secrets file
-      #     echo "Decrypting secrets file: $SECRETS_FILE_PATH"
-      #     sops -d "$SECRETS_FILE_PATH" | kubectl apply -f -
+          # Decrypt only the secrets file
+          echo "Decrypting secrets file: $SECRETS_FILE_PATH"
+          sops -d "$SECRETS_FILE_PATH" | kubectl apply -f -
 
       # Step 2: Fetch and Source the Env File
       - name: Fetch and Source Env File
