updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,19 +55,19 @@ jobs:
 
 
       # Step 3: Install AWS CLI
-      - name: Install or Update AWS CLI v2
-        run: |
-          if ! command -v aws &> /dev/null; then
-            echo "AWS CLI not found, installing..."
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            cd aws
-            sudo ./install
-          else
-            echo "AWS CLI is already installed, updating..."
-            sudo ./aws/install --update
-          fi
-          aws --version
+      # - name: Install or Update AWS CLI v2
+      #   run: |
+      #     if ! command -v aws &> /dev/null; then
+      #       echo "AWS CLI not found, installing..."
+      #       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+      #       unzip awscliv2.zip
+      #       cd aws
+      #       sudo ./install
+      #     else
+      #       echo "AWS CLI is already installed, updating..."
+      #       sudo ./aws/install --update
+      #     fi
+      #     aws --version
 
 
       # Step 4: Configure AWS CLI
