updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -115,8 +115,8 @@ jobs:
           CHART_DIR=$(find "$CHARTS_DIR" -type d -name "$SERVICE_NAME" -exec test -f {}/Chart.yaml \; -print -quit)
           
           if [ -z "$CHART_DIR" ]; then
-            echo "Error: No Helm chart found for service '$SERVICE_NAME' in $CHARTS_DIR."
-            exit 1
+              echo "Error: No Helm chart found for service '$SERVICE_NAME' in $CHARTS_DIR."
+              exit 1
           fi
           
           echo "Found Helm chart for '$SERVICE_NAME' at: $CHART_DIR"
@@ -137,6 +137,11 @@ jobs:
             -f "$CHART_DIR/values.yaml" \
             --set image.tag="${DOCKER_IMAGE##*:}" \
             --set global.domain="$DOMAIN_NAME"  # Pass the DOMAIN_NAME to global.domain in Helm chart
+        shell: /usr/bin/bash -e {0}
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
 
       # Step 8: Configure Ingress Resource
       - name: Configure Ingress Resource
